from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^cye/loc_empresa/$', views.loc_empresa_list),
    re_path(r'^cye/loc_empresa/(?P<pk>\w+)/$', views.loc_empresa_detail),
    re_path(r'^cye/sede/$', views.sede_list),
    re_path(r'^cye/sede/(?P<pk>\w+)/$', views.sede_detail),
    re_path(r'^cye/centro_de_coste/$', views.centro_de_coste_list),
    re_path(r'^cye/centro_de_coste/(?P<pk>[0-9]+)/$', views.centro_de_coste_detail),
    re_path(r'^cye/empleado/$', views.empleado_list),
    re_path(r'^cye/empleado/(?P<pk>[0-9]+)/$', views.empleado_detail),
    re_path(r'^cye/activo_empleado/$', views.activo_empleado_list),
    re_path(r'^cye/activo_empleado/(?P<pk>[0-9]+)/$', views.activo_empleado_detail),
    re_path(r'^cye/administrador/$', views.administrador_list),
    re_path(r'^cye/administrador/(?P<pk>[0-9]+)/$', views.administrador_detail),
    re_path(r'^cye/nivel_acceso/$', views.nivel_acceso_list),
    re_path(r'^cye/nivel_acceso/(?P<pk>[0-9]+)/$', views.nivel_acceso_detail),
    re_path(r'^cye/tipo/$', views.tipo_list),
    re_path(r'^cye/tipo/(?P<pk>[0-9]+)/$', views.tipo_detail),
    re_path(r'^cye/activo_ti/$', views.activo_ti_list),
    re_path(r'^cye/activo_ti/(?P<pk>[0-9]+)/$', views.activo_ti_detail),
    re_path(r'^cye/activo_prov/$', views.activo_prov_list),
    re_path(r'^cye/activo_prov/(?P<pk>[0-9]+)/$', views.activo_prov_detail),
    re_path(r'^cye/prov_servicio/$', views.prov_servicio_list),
    re_path(r'^cye/prov_servicio/(?P<pk>[0-9]+)/$', views.prov_servicio_detail),
    re_path(r'^cye/proveedor/$', views.proveedor_list),
    re_path(r'^cye/proveedor/(?P<pk>[0-9]+)/$', views.proveedor_detail),
    re_path(r'^cye/servicio/$', views.servicio_list),
    re_path(r'^cye/servicio/(?P<pk>[0-9]+)/$', views.servicio_detail),
    re_path(r'^cye/empresa/$', views.empresa_list),
    re_path(r'^cye/empresa/(?P<pk>[0-9]+)/$', views.empresa_detail),
    re_path(r'^cye/contrato/$', views.contrato_list),
    re_path(r'^cye/contrato/(?P<pk>[0-9]+)/$', views.contrato_detail),
    re_path(r'^cye/activo_contrato/$', views.activo_contrato_list),
    re_path(r'^cye/activo_contrato/(?P<pk>[0-9]+)/$', views.activo_contrato_detail),
]